name: lucked/bootstrap-form-builder-1
author:
  name: Lucas rodrigues araujo
  email: lucked@hotmail.com
  url: null
copyright: 2015 Lucas rodrigues araujo
description: Simple Form Builder for Bootstrap 3
